// Generated by delombok at Mon Sep 05 01:05:25 CEST 2011
package jskills.factorgraphs;

public class KeyedVariable<TKey, TValue> extends Variable<TValue> {
	private final TKey key;
	
	public KeyedVariable(TKey key, TValue prior, String name, Object... args) {
		super(prior, name, args);
		this.key = key;
	}
	
	public TKey getKey() {
		return key;
	}
}