// Generated by delombok at Mon Sep 05 01:05:25 CEST 2011
package jskills.factorgraphs

class Variable[T](prior: T, name: String) {
  def this(prior: T, name: String, args: Any*) {
    this(prior, format(name, args))
    resetToPrior
  }

  var value: T = prior

  def resetToPrior() { value = prior }

  override def toString() = name
}